<?php
/*
 * VoiceAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace VoiceAPILib\Tests;

use VoiceAPILib\Exceptions\ApiException;
use VoiceAPILib\Exceptions;
use VoiceAPILib\ApiHelper;
use VoiceAPILib\Models;
use PHPUnit\Framework\TestCase;

class QueueControllerTest extends TestCase
{
    /**
     * @var \VoiceAPILib\Controllers\QueueController Controller instance
     */
    protected static $controller;

    /**
     * @var HttpCallBackCatcher Callback
     */
    protected static $httpResponse;

    /**
     * Setup test class
     */
    public static function setUpBeforeClass(): void
    {
        self::$httpResponse = new HttpCallBackCatcher();
        self::$controller = ClientFactory::create(self::$httpResponse)->getQueueController();
    }


    /**
     * Todo Add description for test testQueueNew
     */
    public function testQueueNew()
    {
        // Parameters for the API call
        $body = TestHelper::getJsonMapper()->mapClass(json_decode(
            '{
  "queue_name": "queue-151-3",
  "ring_strategy": "ringall"
}'),
            'VoiceAPILib\Models\\QueueNewRequest'
        );

        // Set callback and perform API call
        $result = null;
        try {
            $result = self::$controller->queueNew($body);
        } catch (ApiException $e) {
        }

        // Test response code
        $this->assertEquals(
            200,
            self::$httpResponse->getResponse()->getStatusCode(),
            "Status is not 200"
        );

        // Test headers
        $headers = [];
        $headers['Content-Type'] = null ;
        $headers['Date'] = null ;
        $headers['Server'] = null ;
        $headers['X-Powered-By'] = null ;
        $headers['Content-Length'] = null ;
        $headers['ETag'] = null ;
        $headers['Keep-Alive'] = null ;
        $headers['Connection'] = null ;
        
        $this->assertTrue(
            TestHelper::areHeadersProperSubsetOf($headers, self::$httpResponse->getResponse()->getHeaders(), true),
            "Headers do not match"
        );

        // Test whether the captured response is as we expected
        $this->assertNotNull($result, "Result does not exist");

        $this->assertTrue(
            TestHelper::isJsonObjectProperSubsetOf(
                '{
  "response": true,
  "data": {
    "queue_name": "queue-151-3",
    "ring_str' .
                'ategy": "ringall"
  }
}',
                self::$httpResponse->getResponse()->getRawBody(),
                false,
                true,
                false
            ),
            "Response body does not match in keys"
        );
    }

    /**
     * Todo Add description for test testQueueList
     */
    public function testQueueList()
    {

        // Set callback and perform API call
        $result = null;
        try {
            $result = self::$controller->queueList();
        } catch (ApiException $e) {
        }

        // Test response code
        $this->assertEquals(
            200,
            self::$httpResponse->getResponse()->getStatusCode(),
            "Status is not 200"
        );

        // Test headers
        $headers = [];
        $headers['Content-Type'] = null ;
        $headers['Date'] = null ;
        $headers['Server'] = null ;
        $headers['X-Powered-By'] = null ;
        $headers['Content-Length'] = null ;
        $headers['ETag'] = null ;
        $headers['Keep-Alive'] = null ;
        $headers['Connection'] = null ;
        
        $this->assertTrue(
            TestHelper::areHeadersProperSubsetOf($headers, self::$httpResponse->getResponse()->getHeaders(), true),
            "Headers do not match"
        );

        // Test whether the captured response is as we expected
        $this->assertNotNull($result, "Result does not exist");

        $this->assertTrue(
            TestHelper::isJsonObjectProperSubsetOf(
                '{
  "response": true,
  "data": [
    {
      "queue_id": 35,
      "queue_name' .
                '": "96789665",
      "musiclass": "default",
      "strategy": "ringall",
      "' .
                'members": [
        {
          "member": "SIP/968976567"
        }
      ]
   ' .
                ' },
    {
      "queue_id": 36,
      "queue_name": "96queue-151-3",
      "musi' .
                'class": "default",
      "strategy": "ringall",
      "members": []
    }
  ]
}',
                self::$httpResponse->getResponse()->getRawBody(),
                false,
                true,
                false
            ),
            "Response body does not match in keys"
        );
    }
}
