<?php

declare(strict_types=1);

/*
 * VoiceAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace VoiceAPILib\Tests;

class ClientFactory
{
    public static function create(HttpCallBackCatcher $httpCallback): \VoiceAPILib\VoiceAPIClient
    {
        $client = (new \VoiceAPILib\VoiceAPIClient(static::getConfigurationFromEnvironment()))
            ->withConfiguration(static::getTestConfiguration($httpCallback));
        return $client;
    }

    public static function getTestConfiguration(HttpCallBackCatcher $httpCallback): array
    {
        return ['httpCallback' => $httpCallback];
    }

    public static function getConfigurationFromEnvironment(): array
    {
        $config = [];
        $timeout = getenv('VOICE_API_LIB_TIMEOUT');
        $numberOfRetries = getenv('VOICE_API_LIB_NUMBER_OF_RETRIES');
        $maximumRetryWaitTime = getenv('VOICE_API_LIB_MAXIMUM_RETRY_WAIT_TIME');
        $environment = getenv('VOICE_API_LIB_ENVIRONMENT');
        $username = getenv('VOICE_API_LIB_USERNAME');
        $password = getenv('VOICE_API_LIB_PASSWORD');

        if ($timeout !== false && \is_numeric($timeout)) {
            $config['timeout'] = intval($timeout);
        }

        if ($numberOfRetries !== false && \is_numeric($numberOfRetries)) {
            $config['numberOfRetries'] = intval($numberOfRetries);
        }

        if ($maximumRetryWaitTime !== false && \is_numeric($maximumRetryWaitTime)) {
            $config['maximumRetryWaitTime'] = intval($maximumRetryWaitTime);
        }

        if ($environment !== false) {
            $config['environment'] = $environment;
        }

        if ($username !== false) {
            $config['username'] = $username;
        }

        if ($password !== false) {
            $config['password'] = $password;
        }

        return $config;
    }
}
