<?php

declare(strict_types=1);

/*
 * VoiceAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace VoiceAPILib;

/**
 * Baseurl aliases
 */
class Server
{
    public const SERVER_1 = 'Server 1';
}
